/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ResumeNFT } from "./ResumeNFT";
export type { VerificationManager } from "./VerificationManager";
