/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ResumeNFT__factory } from "./ResumeNFT__factory";
export { VerificationManager__factory } from "./VerificationManager__factory";
