// Auto-generated by deployment script - DO NOT EDIT MANUALLY
import { ContractAddresses } from '../types';

export const contractAddresses: ContractAddresses = {
  "verificationManager": "0x59228D0C863A491E197B5fD44699eDBFc88874F1",
  "resumeNFT": "0x793e72b71d78a7D05d34f634C361e2bccdE0bc96",
  "networkName": "sepolia",
  "deploymentTimestamp": "2025-06-13T21:08:50.626Z"
};

export default contractAddresses;
